version: "3.9"

services:

  web:
    extends:
      service: nginx
      file: nginx/docker-compose.yml

#    networks:
#      - host
#    networks:
#      - $NET_NAME

    network_mode: host
#    dns_opt:
#      -
    dns:
      - localhost
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45
#    extra_hosts:
#      - 'hostname.local:192.168.0.10'
  #    network_mode: bridge

#    ports:
#      - 9000:8080

#    build: ./nginx
#    container_name: nginx
##    command: bash run.sh"
##      - /bin/bash -c "./nginx/run.sh"
#
#    environment:
#      - DB=5555
#    env_file: .env
#    ports:
#      - $PORT:8080
#    restart: unless-stopped
##    tty: true
#    volumes:
#      - type: bind
#        source: $PWD/nginx/test
#        target: /test

  #      - bashhistory:/commandhistory
#      - ./test.txt:/test.txt

  bash:
    build: ./bash
    profiles: ["off"]
    container_name: bash
    restart: unless-stopped

  mongodb:
    image: mongo
    profiles: ["off"]
    container_name: mongodb
    env_file: ./db/.env
    volumes:
      - ./db/mongodb/database:/data/db
    ports:
      - 4040:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

#networks:
#  simple:
#    name: $NET_NAME

#networks:
#  host:
#    external: true
#    name: host

volumes:
  bashhistory:
