version: "3.9"

services:

  nginx:
    build: ./nginx
    container_name: nginx
#    expose:
#      - 8080
    ports:
      - 9000:8080
    restart: unless-stopped

  bash:
    build: ./bash
#    profiles:
#      - "off"
    container_name: bash
    restart: unless-stopped

  mongodb:
    image: mongo
#    profiles:
#      - "off"
    container_name: mongodb
    env_file: ./db/.env
    volumes:
      - ./db/mongodb/database:/data/db
    ports:
      - 4040:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 0.0.0.0:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  mbank:
