version: "3.9"

services:

  nginx:
    build:
      context: ../
      dockerfile: ./nginx/Dockerfile.nginx
    env_file: .env
    ports:
      - $PORT:8080
#      - 9000:8080
    restart: unless-stopped
#    tty: true
    volumes:
      - bashhistory:/commandhistory

networks:
  mbank:

volumes:
  bashhistory:
