version: "3.9"

services:

  nginx:
    build:
      context: ../
      dockerfile: ./nginx/Dockerfile
#      network: host
    env_file: .env
    container_name: web
    hostname: web
#    networks:
#      - host
#    network_mode: bridge
#    extra_hosts:
#      - web2:172.21.0.3
#    hosts:
#      - web2:172.21.0.3
#    network_mode: host
#    https://habr:com/ru/company/ruvds/blog/450312/:
#    ports:
#      - 8080:8080
#      - $PORT:8080
    restart: unless-stopped
#    tty: true
    volumes:
      - bashhistory:/commandhistory
      - type: bind
        source: $PWD/nginx/test
        target: /test

#networks:
#  $NET_NAME:

volumes:
  bashhistory:
